package it.water.company.api;

import it.water.core.api.service.BaseEntitySystemApi;

import it.water.company.model.Company;

/**
 * @Generated by Water Generator
 * This interface defines the internally exposed methods for the entity and allows interaction with it bypassing permission system.
 * The main goals of CompanySystemApi is to validate the entity and pass it to the persistence layer.
 *
 */
public interface CompanySystemApi extends BaseEntitySystemApi<Company> {

    Company findByVirtualHost(String virtualHost);
}
