package it.water.company.api;

import it.water.core.api.service.BaseEntityApi;

import it.water.company.model.Company;

/**
 * @Generated by Water Generator
 * This interface defines the externally exposed methods for the entity and allows interaction with it through a permission system.
 *
 */
public interface CompanyApi extends BaseEntityApi<Company> {

    /**
     * Returns the company selected in the caller's tenant-scoped security context.
     */
    Company findCurrent();
}
