package it.water.company.api;

import it.water.company.model.Company;
import it.water.core.api.repository.BaseRepository;

/**
 * @Generated by Water Generator
 * Interface component for Company Repository.
 * It is used for CRUD operations, and to interact with the persistence layer.
 */
public interface CompanyRepository extends BaseRepository<Company> {

    Company findByVirtualHost(String virtualHost);
}
