package it.water.company.service;

import it.water.company.api.CompanyRepository;
import it.water.company.api.CompanySystemApi;
import it.water.company.model.Company;
import it.water.core.api.registry.filter.ComponentFilterBuilder;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.core.interceptors.annotations.Inject;
import it.water.repository.service.BaseEntitySystemServiceImpl;
import it.water.repository.entity.model.exceptions.DuplicateEntityException;
import lombok.Getter;
import lombok.Setter;


/**
 * @Generated by Water Generator
 * System Service Api Class for Company entity.
 */
@FrameworkComponent
public class CompanySystemServiceImpl extends BaseEntitySystemServiceImpl<Company> implements CompanySystemApi {
    @Inject
    @Getter
    @Setter
    private CompanyRepository repository;

    @Inject
    @Setter
    private ComponentFilterBuilder componentFilterBuilder;

    public CompanySystemServiceImpl() {
        super(Company.class);
    }

    @Override
    public Company save(Company entity) {
        normalizeVirtualHost(entity);
        ensureVirtualHostAvailable(entity);
        return super.save(entity);
    }

    @Override
    public Company update(Company entity) {
        normalizeVirtualHost(entity);
        ensureVirtualHostAvailable(entity);
        return super.update(entity);
    }

    @Override
    public Company findByVirtualHost(String virtualHost) {
        return repository.findByVirtualHost(VirtualHostNormalizer.normalize(virtualHost));
    }

    private void normalizeVirtualHost(Company entity) {
        if (entity != null && entity.getVirtualHost() != null) {
            entity.setVirtualHost(VirtualHostNormalizer.normalize(entity.getVirtualHost()));
        }
    }

    private void ensureVirtualHostAvailable(Company entity) {
        if (entity == null || entity.getVirtualHost() == null) {
            return;
        }
        Company existing = repository.findByVirtualHost(entity.getVirtualHost());
        if (existing != null && existing.getId() != entity.getId()) {
            throw new DuplicateEntityException(new String[]{"virtualHost"});
        }
    }
}
