
package it.water.company.service.rest;

import it.water.company.api.CompanyApi;
import it.water.company.api.rest.CompanyRestApi;
import it.water.company.model.Company;
import it.water.core.api.service.BaseEntityApi;
import it.water.core.api.service.rest.FrameworkRestController;
import it.water.core.interceptors.annotations.Inject;
import it.water.service.rest.persistence.BaseEntityRestApi;
import lombok.Setter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/**
 * @Generated by Water Generator
 * Rest Api Class for Company entity.
 */
@FrameworkRestController(referredRestApi = CompanyRestApi.class)
public class CompanyRestControllerImpl extends BaseEntityRestApi<Company> implements CompanyRestApi {
    @SuppressWarnings({ "java:S1068", "unused" }) //still mantain the variable even if not used
    private static Logger log = LoggerFactory.getLogger(CompanyRestControllerImpl.class.getName());

    @Inject
    @Setter
    private CompanyApi companyApi;

    @Override
    protected BaseEntityApi<Company> getEntityService() {
        return companyApi;
    }

    @Override
    public Company findCurrent() {
        return companyApi.findCurrent();
    }

}
