package it.water.company.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonView;
import it.water.core.api.entity.shared.SharedEntity;
import it.water.core.api.permission.ProtectedEntity;
import it.water.core.api.service.rest.WaterJsonView;
import it.water.core.permission.action.CrudActions;
import it.water.core.permission.annotations.AccessControl;
import it.water.core.permission.annotations.DefaultRoleAccess;
import it.water.core.validation.annotations.NoMalitiusCode;
import it.water.core.validation.annotations.NotNullOnPersist;
import it.water.repository.jpa.model.AbstractJpaExpandableEntity;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.Size;
import lombok.*;


/**
 * @Generated by Water Generator
 * Company Entity Class.
 */
//JPA
@Entity
@Table(
        uniqueConstraints = {
                @UniqueConstraint(columnNames = {"vatNumber"})
                // virtualHost uniqueness is enforced (null-safe) in CompanySystemServiceImpl.ensureVirtualHostAvailable.
                // A @UniqueConstraint here would route through the generic DuplicateConstraintValidator, which treats
                // a null value as IS NULL and would flag two companies without a virtualHost as false duplicates.
        })
@Access(AccessType.FIELD)
//Lombok
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@RequiredArgsConstructor
@Getter
@Setter(AccessLevel.PROTECTED)
@ToString
@EqualsAndHashCode(callSuper = true, of = {"vatNumber"})
//Actions and default roles access
@AccessControl(availableActions = {CrudActions.SAVE, CrudActions.UPDATE, CrudActions.FIND, CrudActions.FIND_ALL, CrudActions.REMOVE},
        rolesPermissions = {
                //Admin role can do everything
                @DefaultRoleAccess(roleName = Company.DEFAULT_MANAGER_ROLE, actions = {CrudActions.SAVE, CrudActions.UPDATE, CrudActions.FIND, CrudActions.FIND_ALL, CrudActions.REMOVE}),
                //Viwer has read only access
                @DefaultRoleAccess(roleName = Company.DEFAULT_VIEWER_ROLE, actions = {CrudActions.FIND, CrudActions.FIND_ALL}),
                //Editor can do anything but remove
                @DefaultRoleAccess(roleName = Company.DEFAULT_EDITOR_ROLE, actions = {CrudActions.SAVE, CrudActions.UPDATE, CrudActions.FIND, CrudActions.FIND_ALL})
        })
public class Company extends AbstractJpaExpandableEntity implements ProtectedEntity, SharedEntity {

    public static final String DEFAULT_MANAGER_ROLE = "companyManager";
    public static final String DEFAULT_VIEWER_ROLE = "companyViewer";
    public static final String DEFAULT_EDITOR_ROLE = "companyEditor";

    @JsonView({WaterJsonView.Extended.class})
    @NotNullOnPersist
    @NotEmpty
    @NoMalitiusCode
    @Size(max = 255)
    @Setter
    @NonNull
    private String businessName;

    /**
     * Company invoice address
     */
    @JsonView({WaterJsonView.Extended.class})
    @NotNullOnPersist
    @NotEmpty
    @NoMalitiusCode
    @Size(max = 255)
    @NonNull
    private String invoiceAddress;

    /**
     * Company city
     */
    @JsonView({WaterJsonView.Extended.class})
    @NotNullOnPersist
    @NotEmpty
    @NoMalitiusCode
    @Size(max = 255)
    @NonNull
    private String city;

    /**
     * Company city postal code
     */
    @JsonView({WaterJsonView.Extended.class})
    @NotNullOnPersist
    @NotEmpty
    @NoMalitiusCode
    @Size(max = 255)
    @NonNull
    private String postalCode;

    /**
     * Company nation
     */
    @NotNullOnPersist
    @NotEmpty
    @NoMalitiusCode
    @Size(max = 255)
    @JsonView({WaterJsonView.Extended.class})
    @NonNull
    private String nation;

    /**
     * Company vat number
     */
    @JsonView({WaterJsonView.Extended.class})
    @NotNullOnPersist
    @NotEmpty
    @NoMalitiusCode
    @Size(max = 255)
    @NonNull
    private String vatNumber;

    /**
     * Hostname used to resolve the active company during authentication.
     * It is normalized to lower-case without scheme, port or trailing dot.
     */
    @JsonView({WaterJsonView.Extended.class})
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @NoMalitiusCode
    @Size(max = 255)
    @Setter
    private String virtualHost;

    /**
     * Company creator
     */
    @JsonView({WaterJsonView.Extended.class})
    @Setter
    @NonNull
    @JsonIgnore
    private Long ownerUserId;

}
